#+TITLE: Es2660

* Wildcard Pointers
- Use 3 points
- Ask about assumptions etc using ennis
** Questions
* Week 2 Wildcard
1. Literal (what is the meaning of this term?)
2. Reorganization (what are the main ideas?)
3. Inferential (what can we infer from the choice of words/phrases?)
4. Evaluation (are the facts accurate? do the arguments convince you?)
5. Appreciation (implications, conclusions, connection to the real world)
** Asking Questions on the Black Tech article
1. Literal (what is the meaning of this term?)
2. Reorganization (what are the main ideas?)
3. Inferential (what can we infer from the choice of words/phrases?)
4. Evaluation (are the facts accurate? do the arguments convince you?)
5. Appreciation (implications, conclusions, connection to the real world)
* Week 3
** Ennis
1. Why is critical thinking important? (Level 4)
2. What are the disadvantages of not being able to think critically? (Level 3)
3. How are elementary graphs and maths relevant to critical thinking? (Level 2)
4. What does "non sequitur" mean? (Level 1)
5. As a critical thinker, what do we need to do when someone makes an argument?
   (Level 2)
** Jack (Exercise 3)
- What kind of boy is Jack?
  - Courageous (to fight the giant as a child)
  - Thoughtful/gullible (sold the cow for beans)
  - Trusting (believed the fairy's words)
- What claims are made, and by whom, in the video?
  + By the fairy, but not verified by mother (who was not made)
- What values are being prompted?
  - Courage
  - "Justice"/Vengeance
- Assumptions
  + Giants are always bad
  + Good things will always happen to you by a stroke of luck
- Different points of view?
  + Jack got punished, eg. sent to jail being a murderer
- POV
  - right too what is yours
  - justice/vengeance?
** Red Riding Hood
- Wolf is a sentient creature. Is it ok to kill them?
- Are all wolves bad? Maybe in the farming era, but not in modern day as
  endangered species.
- Vigilantism of huntsman
- Supression of curiosity of children
- Why is she not accompanied by an adult?
- What is with the privacy of the grandmother's house and property?
* Week 4
** CA2 Acronym Brainstorm
*** Keywords
- Fallacy
- Judge
- Define
- Reason
- Evidence
- Sources
- Observations
- Alternatives
- Deduce
- Assumptions
- Doubt
*** Acronym
Check the *S*ources, *O*bserve, *D*oubt, *A*lternatives
* CA2
Question, Understand (by collecting more info), Evaluate (claim, arguments,
conclusion), Synthesize (alternative viewpoints), Take a stand
** My Analysis
*** Question
- Why is no one talking about the change algorithms and AI systems bring?
- Why is there no accountability regardless of the systems in place?
- Why will a "digital welfare state" disadvantage the low-income and vulnerable?
- Seems that the Aadhaar system was faulty. Is that the real intention of the
  system? Should we blame the existence of the system or poor engineering of the
  system instead?
- Is the problem here only because that the systems were "digital"? Will we not
  have the same problems of neglection?
- Algorithmic decision should not be discussed together with Aadhaar, since the
  latter do not involve any such algorithms, at least not described or
  discussed.
- The concern is the "closedness" of digital systems. We need to thoroughly
  understand the inner workings and implications, and in such critical
  infrastructure, open sourcing the code for auditing and supervision by the
  public is necessary.
*** Evaluate
- Claim: Digital systems always neglect the poor, needy, and the non-tech savvy.
  I think this is true, especially those without human intervention.
- Claim: Therefore digital systems such as Aadhaar are bad.
  I disagree. It is the system owner's reposibility to introduce this system to
  the rest of India.
- Claim: Algorithmic systems should not be trusted to make decisions.
  I agree to a certain extent. If you understand the logical flow of the
  algorithm, and the algorithm is basically you making decisions at a higher
  speed (with you agreeing with every single deduction made along the way) then
  you should accept the deduction output. However if you trust a black box
  system, what can I say.
*** Synthesize
- In a country of 1.4 billion, India has every reason to deploy a digital
  system, but on the premise of phasing out the original system slowly and
  paying more attention to those vulnerable to this change.
- Changing from an analog system to a digital system for registration is like
  using a chainsaw to replace an axe, there is no good or bad. It is indeed more
  efficient, but you have to ensure everyone has access to fuel to run the
  chainsaw. No one should blame the chainsaw instead.
- Algorithmic systems and big data systems have subtleties, they recognize
  patterns but rarely underlying logic, and there should be a need to separate
  those two. For example, if you conclude that if someone stays in a
  crime-infested neighbourhood is a criminal, this is a data-based deduction;
  however if you look at their poor living conditions and deduce that there
  might be a lack of common resources, this is a valid deduction that can be
  even deduced from a (logical) algori deduction that can be even deduced from a
  (logical) algorithm.
* Week 6
** Monday - Group A and B
*** Group B
**** JARVIS
Judge Arguments, Ask Questions, Reasoning, Verify Credibility, Inform yourself,
Summarize
**** Questions
- Judge is actually looking? Not judging? What is the basis of judging?
- Verify with fallacies?
** Friday - Group C and D
*** Group C
CEASE
**** Clarify claims
**** Evaluate the evidence
- sources, cross check
**** Analyze arguments
- eg. search for logical fallacies
**** Search for new relevant information
**** End with overview or judgement
*** Group D
RADAR
**** Relate to the issue
**** Audit arguments
**** Detect fallacies and Assumptions
**** Account for alternative viewpoints
**** Review opinion
* Week 7
** Monday
*** Fish Bowl on Internet Accessibility
https://qz.com/1407450/theres-already-a-blueprint-for-a-more-accessible-internet/
- The video and article claims that there has not been enough effort to make the
  internet more accessible to those visually or aurally impaired.
  + I agree with the article. Written in 2018, the captioning abilities on
    youtube for the English language is more mature now.
  + Web pages are also getting visually focused, with many standard-breaching
    practices in order to create visually focused pages. For example, a passage
    might be split up into chucks in different containers to organize in to a
    visually appealing manner, breaking a text-to-speech engine.
- However I think accessibility is not something someone will actively take care
  of unless they been through it. These standards should be enforced in a
  meaningful way, such as bootstrapped into the starting template of web frameworks.
