#+TITLE: MA2108S Mathematical Analysis
#+OPTIONS: toc:nil
* E-lecture 7: Open sets in metric spaces
1. *Definition* Let $<M,\rho>$ be a metric space. A subset G of M is an open
   subset of M if for every $x \in G$, there exists r > 0 so that $B[x,r] \subset G$.
* Week 6 Tutorial
** [G] Exercise 4.1, Question 11
We show that $\lim_{x \to 0}f(x) = 0$.
Let $\epsilon > 0$ be given. Then we choose $\delta = \frac{1}{2}$ such that:
\begin{align*}
\rho(x, 0) \lt \delta &\implies f(x) = 0 \quad (\forall x) \\
                        &\implies \rho(f(x), f(0)) = 0 < \epsilon
\end{align*}

since for any $x \in B[0, 1/2]$, we showed before the fact that
\[ {\frac{1}{p}}^{n} < 1 \quad if \quad p > 1 \quad and \quad n \in \mathbb{N} \]
which implies that
\[ f(x) = x^2 < 1 \quad \forall \quad x \in B[0, 1/2] \]
and thus
\[ [f(x)] = [x^2] = 0 \quad \forall \quad x \in B[0, 1/2] \]
Which is what we wanted to show. \(\square\)
* E-lecture 8: Discontinuous functions on \(\mathbb{R}\)
** Definition
A function \(f: \mathbb{R} \rightarrow \mathbb{R} \) is /nondecreasing/
(/nonincreasing/) if \(x < y \implies f(x) \leq f(y) \quad (f(x) \geq f(y))\). $f$
is /monotone/ if it is either nondecreasing or nonincreasing.
** Proposition 1
Suppose that \( f: \mathbb{R} \rightarrow \mathbb{R} \) is nondecreasing. If \(a
\in \mathbb{R}\), set \[

\]
* Week 7 Assignment
** MA2108S Week 7 Assignment
1. Since *(b)* would imply the forward direction in *(a)*, I will first prove *(b)*.

   *(b)* We want to show that \(U\) is open and \(U \subseteq E\).

   Since, by definition, \(\overline{(E')}\) is closed, \(U = \overline{(E')}'\)
   is open.

   Now we are left to show that \(U \subseteq E\). By contradiction, for any
   \(x \in U \), we assume that \(x \notin E \). Then
   \[
   x \in E' \implies x \in \overline{(E')} = U'
   \]
   A contradiction, as \(x\) cannot be in both \(U\) and \(U'\). Therefore \(U =
   \overline{(E')}'\). \(\square\)

   (a) Let us first prove the forward direction.

   (\(\implies\)) Since \(U\) is an open set, there must exist an \(r > 0\) such
   that \(B[x,r] \subseteq U \subseteq \E\). \(\square\)

   (\(\impliedby\)) Now we are done with the forward direction, we shall prove that for any
   \(x\),
   \[
   \exists r, B[x,r] \subseteq E \implies x \in U
   \].

   We show the contrapositive, \(x \notin U \implies \forall r, B[x,r]
   \nsubseteq E\).

   Then \(x \in U'\). Since \(U \subseteq E\) by the previous part, either
   \( x \in (E - U)\) or \( x \in E'\). The latter case is obvious since if that
   is true,
   \[ x \in B[x,r] \notin E \] and clearly the ball is not fully contained by E.

   Otherwise, we must have \( x \in E - U\). Since \(x \in U' = \overline{(E')} \) which is a
   closed set, then either \( x \in E'\) (which is impossible), or \(x\) is a
   cluster point of \(E'\).

   By the definition of cluster point,
   \[
   \forall r > 0, \exists y \in B[x,r] \quad \text{such that} \quad y \in E'
   \].

   Thus some part of the ball must always be in \(E'\), which gives the result.
   \(\square\)

   (c) Given \(O\) is open, then by definition,
   \[
   \forall x \in O, \exists r, B[x,r] \subseteq O \subseteq E
   \].

   by 1(a), we have \(x\) must be in \(U\) as well, since every element of O
   must be contained by \(U\), \(O \subseteq U\). \(\square\)

2. We first show a lemma:
  
   *Lemma*: \(S, T\) are subsets of metric space \(<M, \rho>\). If
   \(S \subseteq \overline{T} \), then \(\overline{S} \subseteq \overline{T}\).

   _Proof of Lemma:_

   Clearly, if \(S\) is closed, then \(\overline{S} = \overline{T}\).
   Otherwise, then we just consider whether the cluster points of \(S\) are in
   \(\overline{T}\).
   Suppose \(x\) is a cluster point of S, then by definition,
   \[
   B[x, r] \cap S \neq \emptyset
   \]
   and thus,
   \[
   B[x, r] \cap T \supseteq S \neq \emptyset
   \]
   \(x\) is a cluster point of T too, and thus is in \(\overline{T}\). \(\square\)

   Now we shall proceed with the proof.

   (\(\implies\)) We first have \(f(A) \subseteq \overline{f(A)}\). Then looking
   at preimages of both sets,
   \[
   A \subseteq f^{-1}(f(A)) \subseteq f^{-1}(\overline{f(A)})
   \]
   And since \(f\) is continuous, \(\overline{f(A)}\) is closed \(\implies
   f^{-1}(\overline{f(A)})\) is closed.

   Since we have \(A \subseteq f^{-1}(\overline{f(A)}) \), where RHS is a closed set,
   by the lemma, this implies
   \[
   \overline{A} \subseteq f^{-1}(\overline{f(A)})
   \]
   And taking the images of both sets, we have
    \[f(\overline{A}) \subseteq \overline{f(A)}\] \(\square\)

   (\(\impliedby\)) Given that \[f(\overline{A}) \subseteq \overline{f(A)}\], we
   wish to show that if we have a closed set \(V \subseteq M_2\), then
   \(f^{-1}(V)\) is also closed.

   By the assumption, we have
   \[
   f(\overline{f^{-1}(V)}) \subseteq \overline{f(f^{-1}(V))}
   \]
   and since \(f\) need not be injective,
   \[
   f(\overline{f^{-1}(V)}) \subseteq \overline{f(f^{-1}(V))} \subseteq
   \overline{V} = V
   \]
   since V is defined as closed.

   We then have
   \[
   f(\overline{f^{-1}(V)}) \subseteq V
   \]
   which, considering their preimages,
   \[
   \overline{f^{-1}(V)} \subseteq f^{-1}(V)
   \]

   By definition, \(\overline{f^{-1}(V)} = (\{\text{cluster points of V}\} \cup f^{-1}(V))
   \subseteq f^{-1}(V)\),
   which implies \(f^{-1}(V)\) contains all its cluster points. Thus
   \(f^{-1}(V)\) is closed. \(\square\)

3. Set \(a\) such that \(a > f(x) + \epsilon\) for some \(\epsilon > 0\) and \(x
   \in f^{-1}(-\infty, a)\) naturally.

   Then since \(f^{-1}(-\infty, a)\) is open,
   \[
   \exists r > 0 \quad \text{such that} \quad B[x, r] \subseteq f^{-1}(-\infty, a)
   \]
   Since it is known that \((x_n)^\infty_{n=1}\) converges, then given \(r\) as
   defined above, there is an \(N \in \mathbb{N}\) such that for all \(n \geq
   N\),
   \[
   \rho(x_n, x) < r \quad \forall n \geq \mathbb{N}
   \].

   Since we now have
   \[
   x_N, x_{N+1}, \dots \in B[x,r] \subseteq f^{-1}(-\infty, a)
   \]

   and since \(f\) is upper-semicontinuous,
   \[
   f(x_N), f(x_{N+1}), \dots < a
   \]

   Consider \(M_k = sup\{f(x_N), f(x_{N+1}), \dots \} < a \). Thus,
   \[
   \lim_{k \rightarrow \infty} M_k < a \implies
   \limsup_{k \rightarrow \infty} f(x_n) < a = f(x) + \epsilon
   \]

   Now, for every epsilon given, we can find an \(a\), and thus \(N\) such that
   the previous statement is true. Given by Exercise 2.2 Question 2 in
   /Goldberg/,
   \[
   \limsup_{k \rightarrow \infty} f(x_n) < f(x) + \epsilon
   \implies
   \limsup_{k \rightarrow \infty} f(x_n) < f(x)
   \]
   \(\square\)
