#+TITLE: ST2131 Mathematical Statistics

#+LATEX_HEADER: \newtheorem{thm}{Theorem}[section]
#+LATEX_HEADER: \newtheorem{crl}{Corollary}[theorem]
#+LATEX_HEADER: \newtheorem{lemma}{Lemma}[theorem]
#+LATEX_HEADER: \newtheorem{note}{Note}[theorem]
#+LATEX_HEADER: \newtheorem{defn}{Definition}[section]
#+LATEX_HEADER: \newtheorem{ex}{Example}[section]
#+LATEX_HEADER: \newtheorem{obs}{Observation}[section]

* Chapter 4 Parameter Estimation
** Standard Error
SE = SD(sample mean)
* Chapter 6 Hypothesis Testing


** The Neymann-Pearson Paradigm
#+ATTR_LATEX: :options [Statistical Hypothesis]
#+BEGIN_defn
\\
_Statistical hypothesis_ is an assertion/conjecture about the distribution of
one or more random RVs.

_Simple hypothesis_: a SH that completely specifies the distribution

_Complex hypothesis_: otherwise
#+END_defn

#+ATTR_LATEX: :options [Null & Alternative Hypotheses]
#+BEGIN_defn
When deciding which of two hypothesis is true, the *first* is called the _null
hypothesis \(H_0\)_, and the *other*, _alternative hypothesis \(H_A\) or \(H_1\)_

The decision rule is based on a _test statistic_.
#+END_defn

#+ATTR_LATEX: :options [Type I & Type II errors]
#+BEGIN_defn
The decision rule has typically 2 possible conclusions: *reject, or do not
reject* \(H_0\).

_Type I error:_ rejecting \(H_0\) when it is true. The probability of this is
called _significance level_ of the test, \(\alpha\).

_Type II error:_ *accepting* (do not reject) \(H_0\) when it is false. Probability
of this is \(\beta\). _Power of the test_ is probability of *rejecting* \(H_0\)
when it is false, \(1-\beta\).
#+END_defn

#+ATTR_LATEX: :options [Egg Tarts - Normal]
#+BEGIN_ex
Egg tarts weigh, in grams \(N(40, 2^2)\) when made by chefs, but \(N(43, 2^2)\)
when made by a trainee. Given the weight of tarts, is the trainee working today?
#+END_ex
