#+TITLE: UPI2211 Utopia
* Week 6 Monday
** More's Utopia: Foreign Politics, War and Morals in Utopia
*** Foreign Politics
- Idealism
  - Human nature is a treaty by itself, humans are united via feelings and
    emotions
  - And it is more effective than treaties
- Cynicism
  - Giving rewards to people who kill the enemy king, as loyalty is impossible and
    people only care about themselves
*** Policies
- Do not involves citizens in foreign wars
  - Only on a voluntary basis
  - Unless Utopia is invaded, then people are tasked to defend
  - Send whole families to war instead, boost morale
  - Compare to "international army" who fight for others causes
- Tolerant of religious plurality
  - However disallows/looksdown on atheists
  - All religions held in a same church - everything is common to all religions
** Discussions
*** Warfare: hypocrisies and contradictions
- Utopians hire Venalians to fight for themselves
  Problems:
  - "Utopians do not care how many Venalians they send to their deaths" (p.94)
  - They don't care if Venalians are enticed by money to fight one another
  - Saying that Venalians are "naturally designed for war" prevent Utopians to
    question the moralities of their policies
  - Double standards on the value of human life, regarding Utopians and Venalians
  - Can they always be the richest country?

*** Group discussion questions
- Are these policies what More thought was the ideal manner of interstate behavior?
  - Is this Thomas More or Morus? Probably Thomas More
  - Are they ideal? Probably in a efficiency sense, but does it go against their morals?
  - Their reasons for going to war are quite petty
  - Utopia is built on a practical rather than a moral objective
    - For example, religion + afterlife is to regulate moral behaviors
    - Did he want to eliminate the class system? Probably not(?)
- Is a non-contradictory utopia possible? Efficient == moral?
  - Not killing civilians is a efficient/moral way of waging war.(less lives lost) But reasons for waging war might not be moral
  - Impossible. Why?
    - There is just so much you can control. Things can never be absolutely equal
    - There will always be tradeoffs? Also, what is moral then may not be moral now (ie no freedom of choice to live life)
- Is Utopia satiric? If so, why did he still alternate between possible and satiric policies?
  - He wants people to think about his policies
  - Blurs the line between utopia and dystopia - good place and noplace
  - Cover up what he really thought with ridiculous ideas?
* Midterm Assignment
We shall first list down possible topics/areas, based on the forum posts.
** Previous Topics
*** Week 2 Monday
- Are humans innately selfish?
- Why did Plato abandon the healthy city and go for the luxurious city?
- Do you agree with the principle of specialization?
*** Week 2 Thursday - The noble lie's preempt: censorship and the arts
- Does the effect of harmful representations depend on the medium or on the spectator?
- Should we censor content or educate spectators? Are there limits to how much spectators can be educated?
- What ensures that the censors are always right? How should we make trade-offs between individual  freedom and social harmony?
- Does music have objective ethical effects?
*** Week 3 Thursday - The Noble Lie
- Is the noble lie a necessary evil? Or is it optional?
- Will the guardians believe in the noble lie?
- Is the city a utilitarian calculus? Are we enjoying at the cost of sacrificing
  a minority (the guardians)?
- Inequality and leadership? Compared to Singapore, where ministers are paid handsomely?
*** Week 4 Monday - Kallipolis Social arrangements
This week is about more's treatment of women, love/marriage, children, and eugenics.
- Is Plato a feminist?
- How does Plato decide what is a "best" person and hence suitable for reproduction?
- The abolition of the nuclear family
*** Week 4 Thursday
Book 1 of Utopia: How thieves are dealt with, and society in Europe at that time.
- Book 1 as a political commentary, written to contexualise the second book
- Listeria: thieves forced into labour
- The ethics of penal labor - is it ethical?
  - It does not deal with the root cause of feudal landowners
*** Week 5 Monday
Philosopher kings, and what can philosophers do to help kings
**** Morus - You should provide consultation to the kings
By sugarcoating your arguments until they accept what you say one Day
**** Raphael - It is useless
As an adviser you will be corrupted, forced to agree/disagree with others
**** Utopia - 6-hour workday and central planning
Would such command economy and socialistic policies work? Will people be
satisfied with the work conditions or will they revolt? Is this a feasible policy?
*** Week 5 Thursday - Social, Political and Economic Policies in Utopia
**** Is Colonialism allowed/justified?
- Why can you occupy other's space? Is using POWs as slaves justified?
- How can you pleasure yourself upon the suffering of others?
**** Slavery as punishment
- Can this ever work as a form of rehabilitation to allow the criminals to go
  back into the society?
- Tasking them to slaughter animals might just make them more violent
*** Week 6 Monday - Religion and International Policies
**** International Policies
- Believes in human nature rather than treaties to be peaceful
- Will wage war for other countries if their businessmen are cheated
- Voluntary Military recruitment
- Strategy: without bloodshed. Sow seeds of discord and pays for the kiling of
  enemy king
***** Hypocrisies
- Treat Venelians not as humans
- Sowing seeds of discord is not really ethical
**** Religion
- Monotheism, religious tolerance, intolerance against atheism
- Priests hold high position and are revered
** Assessment Rubrics (IMPT)
- It identifies and clearly introduces a specific question or problem raised by
  the text and explains why it is significant and worth discussing
- It considers the question or problem from different angles and responds to the
  texts’ arguments in a way that displays originality, critical acuity, and an
  in-depth understanding of the function, logic, and context of the texts’
  arguments.
- If it cites other academic sources, it engages with them in an honest,
  critical, and thoughtful manner, cites them correctly and appropriately, and
  clearly explains how they support the author’s own argument.
- It offers a brief conclusion that explains what the letter or dialogue has
  contributed and what further questions related to your inquiry might be
  fruitfully explored later.
- It is well-written, clearly structured, and almost entirely free from
  grammatical errors and stylistic infelicities
** Draft 1
Some questions for me to answer first
1. What form am I writing this in?
   A letter from Plato to More
2. What is the problem, and what is its significance
   Plato believes humans are dumb in general, and they need a noble lie.
   1. Nuclear family is dumb and cannot work
   2. Private property is embedded in human nature, communism cannot work.
      Humans are selfish and only with noble lie things can work.
   3. Can complement More on their lack of law - Plato thinks law is not
      necessary given the citizens are indoctrinated by the noble lie and will
      be forced to do good. More believes that human nature itself can replace
      complicated laws.
3. What are the angles I am responding to this problem from?
*** Attempt 1: Nuclear Family
Republic(457c - 466), Utopia 83-85
- Plato: people should just mate a breed favorably. The best humans breed will
  get us the best offspring.
- More: Love is sacred and people should love each other as they are, and the
  sexual relationship which they take is a byproduct of successful marriage.
- Plato: Humans should marry, but that is just a ceremony to achieve state
  control in reproduction.
- Children born from inferior or non-guardian parents must be inferior.
- It is impossible to determine the quality of babies.
Plato for some reason met More, who was spending time with his family. Upon
Plato's visit, More was promptly surprised, but he could not recognize Plato
until the man introduced himself. For some reason, they both speak English

Plato: You must be Thomas More, I ... and had the chance to meet you. I am here
to speak to you about family. Would you have time for such a conversation?

More: Certainly. What is it so important that we must talk about families in our
first and very last meeting?

Plato: Well, since you are such a family man, we shall talk about it once and
for all. In your book "Utopia", which I imagine is an ideal city that you are
trying to construct, in a similar spirit with Kallipolis. You said that people
should live together in a small family, and have one spouse only. What is the
reason for doing so? Since Utopia is so rich, why should it not allow men to
have many wives instead? There is nothing wrong with it, especially when spouses
have already passed the ritual.

More: My dear Plato,
*** Thomas More's letter to Plato
Plato and Thomas More met, in More's time, and having read each
others' work on an ideal city, which Thomas More named as Utopia, and Plato
recorded his as Kallipolis. Both of them stroke up a conversation immediately
after recognizing each other on the street, just before More has to attend a
church service.

More: Hi Plato, your work on Kallipolis was a monumental one, but do you mind
talking about the social policies Socrates mentioned when he was describing how
it can be built?

Plato: Certainly.

More: Then let us first talk about the composition of families. Socrates
proposed the idea of shared spouses and children in Kallipolis, and that is for
the reason of having the best possible offspring in Kallipolis. This is first
driven by the fact that the "need for excellent rulers is indeed extreme"
(/Republic/ 459b). And by observing dogs and birds at Glaucon's home, we decide that since
birds and dogs have the best and most noble offspring by "breeding from the
best"(/Republic/ 459a), and "those in their prime"(/Republic/ 459b), we can have humans do the same
too and have our best people produced generation over generations in the Kallipolis.

Plato: That is true.

More: Now allow me to ask, how are humans directly equal to the animals? Humans
are clearly more superior beings than animals, for human is the species
that is superior than just normal animals, as their souls are immortal and are
unlike animals (/Utopia/ 101). Humans are also only species who "admires the
beauty of the world, enjoys any sort of scent", and "can tell the difference
between a harmony and a discord" (/Utopia/ 79). Since humans distinguished themselves from
animals via their soul, and its qualities, then having citizens with the best possible
soul is our priority. Furthermore, Socrates mentioned that in the Kallipolis,
the guardians have to be "gentle, spirited, and philosophical" (/Republic/ 375c-e), all of
which lies within the soul? One can be gentle in the looks, but evil and
calculating in the soul, spirited in the body, but cowardly when confronted with
hardships, and even more, if one is a fine philosopher, it is not easily
distinguishable from the looks. Since the human body is a mere vessel containing
the soul, which is responsible for what they do and who they are, we shall judge
a person by its soul, just like how you choose the guardians in the Kallipolis.
Since the most prized guardians of the Kallipolis are the strongest at their
thoughts, and thus are suitable to be trained to be guardians, how can we liken
the breeding of animals to humans, or much less, the guardians, whose spirits
are unparalleled?

Plato: Let me repeat your question. So you are opposing the idea of selective
breeding of citizens in Kallipolis, claiming that it might not result in
offspring with desired qualities as Socrates and Glaucon have hoped?

More: That is precisely my question.

Plato: Understand. First, let me ask you a question. I am sure you have horses
in Europe?

More: Certainly, but I think they are unlike humans in many ways.

Plato: Pray let me finish my point. Now, when you choose your horses, are the
tame-looking ones likely to be wild and unwieldy, or are they less likely to
follow order as compared to the wild stallions?

More: I think they are likely to be gentle.

Plato: So it is not entirely unreasonable if we can judge people not just by its
soul, for the body is just a case, as you will agree, which the soul resides,
and a good soul, and a desirable one, will manifest itself to a decent body. As
Socrates mentioned in Book IV, "it seems to me that a fit body doesn't by its
own virtue make the soul good, but instead that the opposite is true - a good
soul by its own virtue makes the body as good as possible." (/Republic/ 403d) If you
consider the contrapositive statement, if a body is not the best, it is unlikely
the soul is made up of amazing virtue, since if the person is of the best in his
mind, the body would not be a disappointing one.

More: That is true, but I think we reached the tough question about body and
souls, which is inherited in reproduction? Is it the just the body or it
includes the soul? This is very contentious about humans, and we have our own
belief in Christianity. Now I would like to hear more from you about this.

Plato: Then let us talk about humans. Do you think the children of thieves, will
all likely to be priests or philosophers in the future? Will they not be born,
unknowingly, with the ability to steal? Or is it more likely that a person with
virtuous family members that will grow up to become a person like his or her
parents?

More: That must be true, regarding the circumstances. However, I think these
examples do not consider the training of children in music and poetry, or even
physical training. (/Republic/ 377a) A child, even though born with a poor background, can
be trained to become a philosopher as well, as long as they learn the ways of
inquiry. I think that even though the chances are higher that a guardians'
children will be of the same caliber, I still think such an outright exclusion
and disregard to humans' ability to learn is contrary to the fact that animals
are fundamentally different from humans. Will humans not learn to adopt the
qualities of gentle, spirited and philosophical as you mentioned, with
appropriate training?

Plato: It is true, but Kallipolis is not created to ensure the happiness and
fairness for each and every of its citizen, but the city is virtuous and happy
as a whole. (/Republic/ 421b) Have you not seen the problem with too many mouths in a
family? The children who are weakest usually suffer from diseases and die a
young age, or from malnourishment. If we try to nurture too many possible
guardians by not selecting them based on breed as you suggested, I am afraid we
will fall to the same fate of overcommitment. Kallipolis' source of wealth and
happiness is by the virtuous guardians who keep the city safe and under control,
and only having an appropriately large amount of them can make sure by the
generations, the city will not fall due to the lack of virtuous guardians. This
way, the makers in the city will have the greatest happiness too, not because of
the multitude in opportunity for sexual intercourse, but because they are
protected by able guardians.

More: So your point is in order to save time, we should just use the heuristics
given by a person's body to assess him for whether he is suitable for mating,
and bear the assumption that guardians are guaranteed to have a higher
probability of having good offspring, in the hope that the future generation
will turn out to be the same, if not better? And this will be regardless of
whether it is fair to each and every soul in Kallipolis as we care only about
the future of the city itself rather than personal gains, even if it means to
live in pain or the unhappiness of not being able to have the chance to
reproduce, and have your own offspring, as I would think is what humans are
naturally conditioned to do.

Plato: Indeed they would not be sad about it, since they believe in the noble
lie that each of them are earthborn brothers, and will fight together to defend
the land in which they live (/Republic/ 414e), as the survival and prosperity of the city
would be their ultimate goal, even if it means to suffer personal losses. In
terms of having offspring, all citizens in Kallipolis will have many mothers and
fathers, also siblings and children too (/Republic/ 461d), and it is this shared ownership
that will overcome the selfish sense of private property.

More: Indeed that is how it is arranged in Kallipolis. I doubt it will work in
any other contemporary settings, including the Utopia I described in my book,
but I can see now how Socrates designed the Kallipolis to be.

Plato: Precisely.

More: Plato, have you also mentioned that all these are packaged in "falsehood
and deception for the benefit of those they rule" by the rulers, which are a
form of drug (/Republic/ 459c). In the case of marriage, the rulers will allow
sophisticated lotteries to favorably pick the best "breed" to marry each other.
Have you thought of what could happen if one day, an inquisitive mind discover
the scheme behind the curtains, and the makers of Kallipolis find out that they
are manipulated to give up their ability to reproduce? You must agree with me
that all animals and humans alike, are "driven by innate necessity to have sex
with one another" (/Republic/ 458d)? Just like you being robbed of your food, will you not
be enraged if you are denied of opportunity to marry someone?

Plato: One certainly will.

More: Now how do you deal with those who saw through the scheme of manipulation
and deem Utopia an unfair city, where the citizens are mindless puppet drugged
with lies and falsehood? Will this not put Kallipolis in danger as this
falsehood is the basis of the building of the city?

Plato: Those who reach such a level of comprehension and intellect, are
extremely rare, for normal humans are incapable of such reasoning without a
philosophical mind. If they truly understand, they should see all the more why
these are put in place; it is to grant the whole city happiness as we mentioned,
not in its parts, but as a whole.

More: I see. I have a church service to attend, so we have to end this
conversation now. I think we can safely say that Socrates likely to have thought
of people as largely incapable of the inquisition of knowledge, and humans are
not much different from animals as they both can possess common qualities, such
as being gentle or spirited? And on the assumption that the noble lie can hold
the city together, people would be fine to be given up their ability to marry
whoever they like as they will accept their marriage arrangement by the rulers?

Plato: I think that is an accurate conclusion for our conversation.

* Week 6 Thursday - Cinnamonia
** Political
*** Decentrailzed government by a few constitutional laws
*** The rest have their own laws, and may the best system emerge victorious
Like the religious system in Utopia
*** Cons: hard to reconcile, for example gun laws in US
** Economic
*** Dual-tier
**** Necessities are paid for
Instead of money, give them electricity, food, water, shelter etc (Universal
Basic Services)
**** More work more pay
However it is hard to regulate how long they work for different professions
**** Cons
However the best states will attract the most citizens, like US states
which might cause overpopulation due to the freedom of movement
** Community, Health, Family
*** Do what you are good at
and leave the rest for AI. If AI is good enough, it can do most of the jobs, and
people can choose what they wanna do
*** Nuclear family
*** Conflict between state intervention and personal freedom/liberty
Which is a problem in Utopia, since we would imagine both in an ideal city
**** Possible solution:
With sufficient education for people to think rationally, and choose the best
option for them.
** Tech and sustainability
Both of these need education/noble lie from young, since we are very idealistic
in forming our policies
*** Sustainable energy
*** Sharing of technology - Open Source
* Week 7 Monday - Walden Two, Chap 8-11
** My reading notes
*** Chapter 8
- 1200 credits a year to get free bills
- currently it is 1h/credit
- unpleasant or unpopular jobs have higher credits, and vice versa
- Workers, Planners, Managers and Scientists
  - Planners make policies and manage managers
    Salary is 600 a year, 2 credits per day, 1 of which physical labor
  - Managers are admin guys of respective professions
  - Scientist same income as manager, 2/3 per day
    - no pure science
    - "A leisure class would grow like a cancer until the strain upon the rest
      of the community became intolerable" (50)
- We must not let big muscles atrophy (52)
- four is more than half of eight. We work more skillfully and faster during the
  first hours of the day (53)
  - Especially you are working for yourself not your boss
- No need for insurance or tavern, since alcohol is to "counteract the fatigue
  and boredom of a mismanaged society"
- Request visitors to work 2 credits a day, and can bring half away
  - However residents need to surrender all income to walden 2
*** Chapter 9
- Decide to work as window cleaners to pay their credits
- Found that it is at first "like prisoners", then "easier than grading or
  reading term papers"
*** Chapter 10
- Frazier says they get rid of hard work, instead of workers in trying times
- Frazier keeps food stock enough for a year, which Castle commented "like
  locusts" (70)
- Walden Two might have some fatal flaw.(71) Frazier seldom know what he was
  talking about, a rank amateur in rural arts.
- 3 rooms, like astronaut's entry, for farmers to get rid their odor to make the
  job more popular (72)
- no one thanked her... this was in accordance of the Walden Two code. (75)
- The Lovely Lady in thin air on thin thread analogy
  - "We prefer the illusion, too... we enjoy floating in air." (76)
  - We are not free from the economic law, but leisure is our levitation.
*** Chapter 11
- What makes a poster interesting, conditional behavior (77)
- What do you do during free time?
- Walden 2 produces art as abundantly as technology
- Golden Age is unintentional. We let civilization run away and see what we can
  do with her lovely colt (Mg chills)
- Everyone is encouraged to learn the arts, and perform or present it as people
  consume them regularly
- Musical families and centers are the environment to condition and make the
  most out of genes.
** Presentation: Walden Two and behaviorism
*** Skinner and Behaviorism
Walden Two uses positive conditioning mainly
- Classical Conditioning
  stimulus, like Pavlov's dog
- Operant Conditioning
  give consequence to an action, eg giving more screen time for practicing piano
Skinner believes there is no free will, but only *reaction to the environment*
*** Construction of Walden Two
- (46) We don't propagandize. That's a basic principle.
  When asked about how to make people select undesirable jobs
- Naturalism
  *Definition*: all beings and phenomenon in the universe are natural and can be
  explained by science.
**** Conditioning examples
Behavior -> Consequence -> New Behavior
1. Sheep touch electric fence -> Sheep electrocuted -> Sheep shuns away
   And thus we can use a string
2. Visit Walden Two -> Guilty -> Work in Walden Two
*** Criticisms against Skinner
1. Takes away purpose, mind and freedom
   Counter: naturalizes instead
2. Behavioral conditioning
   Counter: every civilization does, it, question is whether it is *dehumanizing*
*** Think about:
1. How does Singapore government condition the citizens via policies?
   - Meritocracy itself is a conditioning
     people might lose faith in the society if they work hard and not do well
   - Prof: Giving you grades is conditioning you to work harder
   - Cigarette packs having deterring images
2. If Singapore politicians were to read Walden Two, how would it influence
   their societal ideals?
3. How do you think the conditioning done to us affected our idea of an ideal
   state?
** Discussions
*** Labor market in Walden Two
Is "raising the credits" for more needed, less wanted jobs a better way to
organize the job market?
- Pride and prestige in jobs
  People are not thanked in the society.
  Doctors are not called doctors in Walden Two, stripped away their title
- The paradox that the most menial jobs are the highest hours
*** Behaviorism vs Genetics
- Frazier: culture (environment) is the key to producing artistic talents, genes
  not so
* Week 7 Thursday - Walden Two, Chap 12-15
** Reading notes
*** Chapter 12 - The Nursery
- Babies until 1 stay in a nursery, like an "aquarium" as "fishes (87)"
- Sleep on plastic sheets, without clothing, temperature control, controlled and
  unnatural environment
- obstacles and nuisances are introduced slowly (89)
*** Chapter 13, 14 - Emotional conditioning
- controlled groups for children in groups or exposure to contagious diseases (91)
- using behavorial engineering to eliminate negative emotions such as "anger,
  fear and rage" (92,93)
- Frazier and his planner, Simmons, seek to learn the ways to teach self-control.
- Jesus's technique is to practice the opposite emotion (96)
- But by promising paradise or hellfire might not be effective
- Lollipop and powdered sugar - teach the children to practice self-control by
  taking it out of sight. Then train their tolerances.
- Soup and temptation - first wait for 5 minutes by a song, and then practice by
  coin flips. Heads eat, tails wait for 5 minutes
- "the community must gain their loyalty, when they discover the fears and
  jealousies and diffidences in the world at large." (103)
- "Triumph over nature and over oneself, yes. But over others, never."
- "The unhappiness we deliberately impose are far milder than the normal
  unhappiness from which we offer protection." (104)
*** Chapter 15 - The schooling system
- "we also don't require all our children to develop the same abilities or
  skills." (110)
- "What are these distinctions, anyway, once you have separated education from
  the administration of education?" (111)
- Hands-on, practical education, learn things that are valuable and relevant
- "We teach anatomy in the slaughterhouse, botany in the field..." (112)
- "Freedom is a question, isn't it?" (118)
*** Chapter 16
- Teenage love is encouraged and people can bear children a few years after they
  are physically able
- "We say it wont last... of course!... A thousand forces conspire against it,
  but they are not forces of the nature, but those of an ill-organized society".
- Teens will be financially supported by the state to get married and bear
  children
- In Walden Two, women finish reproducing by around 23, and since the burden of
  childcare is taken care of by the society, she is free to explore her career.
  (122)
- "Puppy love tends nott to be overtly sexual at all. It's usually highly
  idealistic." If a manager feels the couple has great discrepancy in
  intellectual ability or temperament, the marriage is at least postponed or
  cancelled.

*** Chapter 17 - Married live
- Married couples sleep in separate rooms. This is claimed to promote "health,
  convenience and personal freedom" in life after childbearing.
- "Instead of inviting promiscuity, it perpetuates loyalty and ensures any
  continuing affection is genuine."
- "Free affection" and the principle "seduction not expected", so opposite sexes
  can make friends with each other normally and "that goes a long way towards
  satisfying the needs which lead to promiscuity elsewhere."(129)
- Divorce is made pretty much painless with the assessment of a psychologist
  (131)
- The attenuation of the parent-child bond
  1. requires other adults to show affection to children not of their own
  2. allows childless adults to care and show affection
  3. make divorce less traumatic for the children
- The "tradition of slavery" where women "have no choice but to work as a cook
  and cleaning woman", disillusions our false promise of equality in education
  (135-6)
** Presentation
** Debate
* Week 8 Monday - Walden Two, Chap 20-24
** Reading
*** Chap 18-19 (Not assigned)
- Burris, Steve and Rodge went for heavy work, during which Rodge showed great
  interest in joining Walden Two, but Babara, his girlfriend is opposed to this
  way of living, which held him back.
- During dinner, Burris asked Frazier whether Walden Two learnt anything from
  similar communities in the past, and after strong denial at first, Frazier
  said such communities are often idealistically carrying out principles rather
  than experimenting with strategies that improve, which caused their downfall.
  (141)
*** Chapter 20 - The Good Life
- The Good Life is
  - good health
  - not idleness, but enjoyable, voluntary work
  - chance to exercise talents and abilities
  - intimate and satisfying personal contacts
  - relaxation and rest
  - and Frazier claims that this is exhaustive.
- Castle notes that this is under the assumption that human is good by nature,
  which Frazier achieves by behavourial engineering.
- Walden Code:
  - The Ten Commandments
  - Some trivial ones include:
    - Don't talk to outsiders about the affairs of the community.
      Except for Planners, and certain cases
    - (Apprenticeship rule) Explain your work to any member who is interested.
    - Don't gossip about the personal relations of members
    - Don't wait too be introduced before speaking to a stranger, nor bother to
      make introductions if no relevant information is to be communicated.
      Introductions are solely for the purpose of communicating information.
    - The expression of boredom is accepted here to prevent time being wasted.
      The person does not get offended because this is a norm, and this rule
      rids the speaker of the fear of being boring.
    - Disallow public discussion on disagreement on any rule. You can only speak
      to Manager, or Planner if managers reject your disagreement.
    - Cannot publicly display gratitude to any specific person
- Frazier unscientifically insists that the success of Walden Two is due to the
  self control the residents acquired when they were young. (164)
*** Chapter 21 and 22: Healthcare and Public relations
- Walden Two has exceptional healthcare too, similar to Utopia. The dentists,
  for example, have almost nothing to do.
- Castle argues the doctors' training come from the state, rather than Walden Two.
- Frazier: previously designed utopias are in a fictitious world where people
  behave in a different way, but Walden Two uses behavorial engineering to
  create it now and here (180)
- Frazier has no faith in human nature (182), but engineers it to be socially capable.
- Members do not take part in politics and vote as instructed by the Political
  Manager's "Walden Ticket" (183)
- Free to practice any religion, but members have Sunday meetings to
  indoctrinate the Walden Code (185). Walden as a religion provides: (186)
  1. Aid to the sick and needy (healthcare)
  2. Comfort in time of loss (by psychologists)
  3. Genuine comfort - sympathy and affection of many friends (community love)
  4. Hope for a better future (now and here)
*** Chapter 23: Keeping people in Walden Two
- Indoctrination is the safest way of assuring failure. (192)
- Children in Walden Two know the whole outside world and its truth in its
  entirety. With the poverty and suffering, they might just appreciate Walden
  Two even more.
- Assignment: to find poverty in luxury as fast as possible
- Indoctrination masks the happiness and other variables in a community, making
  it unsuitable for experimentation of the rules and therefore incapable of
  progress to stay relevant in changing times.
** Presentation: Frazier - Tyrant or Genius?
*** Frazier, Burris and Skinner
- Frazier acted as a mouthpiece for Skinner
- Fulfilled his God Complex by able to create a fictitious world himself
- Skinner can dabble with his extremist views, on "carrying out" experiments on
  humans
- Burris ans Frazier act like two sides of Skinner
*** Their views
**** Castle's view of Frazier
- Frazier is the midget chess player behind Walden Two
- Frazier might me thought of as ingenious, if his actions are without moral repercussions
- More of a tyrant - sadistic, dubious
**** Burris
**** Steve and Mary
- Too good to be true, must have some kind of catch
** Democracy
- stifling voices from the people
- planner came out with the code, which
*** Points raised
- dissent only raised to the planners
- abduction of scientific method (how) to justify his beliefs
