#+TITLE: UPI2211 Utopia
* Week 6 Monday
** More's Utopia: Foreign Politics, War and Morals in Utopia
*** Foreign Politics
- Idealism
  - Human nature is a treaty by itself, humans are united via feelings and
    emotions
  - And it is more effective than treaties
- Cynicism
  - Giving rewards to people who kill the enemy king, as loyalty is impossible and
    people only care about themselves
*** Policies
- Do not involves citizens in foreign wars
  - Only on a voluntary basis
  - Unless Utopia is invaded, then people are tasked to defend
  - Send whole families to war instead, boost morale
  - Compare to "international army" who fight for others causes
- Tolerant of religious plurality
  - However disallows/looksdown on atheists
  - All religions held in a same church - everything is common to all religions
** Discussions
*** Warfare: hypocrisies and contradictions
- Utopians hire Venalians to fight for themselves
  Problems:
  - "Utopians do not care how many Venalians they send to their deaths" (p.94)
  - They don't care if Venalians are enticed by money to fight one another
  - Saying that Venalians are "naturally designed for war" prevent Utopians to
    question the moralities of their policies
  - Double standards on the value of human life, regarding Utopians and Venalians
  - Can they always be the richest country?

*** Group discussion questions
- Are these policies what More thought was the ideal manner of interstate behavior?
  - Is this Thomas More or Morus? Probably Thomas More
  - Are they ideal? Probably in a efficiency sense, but does it go against their morals?
  - Their reasons for going to war are quite petty
  - Utopia is built on a practical rather than a moral objective
    - For example, religion + afterlife is to regulate moral behaviors
    - Did he want to eliminate the class system? Probably not(?)
- Is a non-contradictory utopia possible? Efficient == moral?
  - Not killing civilians is a efficient/moral way of waging war.(less lives lost) But reasons for waging war might not be moral
  - Impossible. Why?
    - There is just so much you can control. Things can never be absolutely equal
    - There will always be tradeoffs? Also, what is moral then may not be moral now (ie no freedom of choice to live life)
- Is Utopia satiric? If so, why did he still alternate between possible and satiric policies?
  - He wants people to think about his policies
  - Blurs the line between utopia and dystopia - good place and noplace
  - Cover up what he really thought with ridiculous ideas?
* Midterm Assignment
We shall first list down possible topics/areas, based on the forum posts.
** Previous Topics
*** Week 2 Monday
- Are humans innately selfish?
- Why did Plato abandon the healthy city and go for the luxurious city?
- Do you agree with the principle of specialization?
*** Week 2 Thursday - The noble lie's preempt: censorship and the arts
- Does the effect of harmful representations depend on the medium or on the spectator?
- Should we censor content or educate spectators? Are there limits to how much spectators can be educated?
- What ensures that the censors are always right? How should we make trade-offs between individual  freedom and social harmony?
- Does music have objective ethical effects?
*** Week 3 Thursday - The Noble Lie
- Is the noble lie a necessary evil? Or is it optional?
- Will the guardians believe in the noble lie?
- Is the city a utilitarian calculus? Are we enjoying at the cost of sacrificing
  a minority (the guardians)?
- Inequality and leadership? Compared to Singapore, where ministers are paid handsomely?
*** Week 4 Monday - Kallipolis Social arrangements
This week is about more's treatment of women, love/marriage, children, and eugenics.
- Is Plato a feminist?
- How does Plato decide what is a "best" person and hence suitable for reproduction?
- The abolition of the nuclear family
*** Week 4 Thursday
Book 1 of Utopia: How thieves are dealt with, and society in Europe at that time.
- Book 1 as a political commentary, written to contexualise the second book
- Listeria: thieves forced into labour
- The ethics of penal labor - is it ethical?
  - It does not deal with the root cause of feudal landowners
*** Week 5 Monday
Philosopher kings, and what can philosophers do to help kings
**** Morus - You should provide consultation to the kings
By sugarcoating your arguments until they accept what you say one Day
**** Raphael - It is useless
As an adviser you will be corrupted, forced to agree/disagree with others
**** Utopia - 6-hour workday and central planning
Would such command economy and socialistic policies work? Will people be
satisfied with the work conditions or will they revolt? Is this a feasible policy?
*** Week 5 Thursday - Social, Political and Economic Policies in Utopia
**** Is Colonialism allowed/justified?
- Why can you occupy other's space? Is using POWs as slaves justified?
- How can you pleasure yourself upon the suffering of others?
**** Slavery as punishment
- Can this ever work as a form of rehabilitation to allow the criminals to go
  back into the society?
- Tasking them to slaughter animals might just make them more violent
*** Week 6 Monday - Religion and International Policies
**** International Policies
- Believes in human nature rather than treaties to be peaceful
- Will wage war for other countries if their businessmen are cheated
- Voluntary Military recruitment
- Strategy: without bloodshed. Sow seeds of discord and pays for the kiling of
  enemy king
***** Hypocrisies
- Treat Venelians not as humans
- Sowing seeds of discord is not really ethical
**** Religion
- Monotheism, religious tolerance, intolerance against atheism
- Priests hold high position and are revered
** Assessment Rubrics (IMPT)
- It identifies and clearly introduces a specific question or problem raised by
  the text and explains why it is significant and worth discussing
- It considers the question or problem from different angles and responds to the
  texts’ arguments in a way that displays originality, critical acuity, and an
  in-depth understanding of the function, logic, and context of the texts’
  arguments.
- If it cites other academic sources, it engages with them in an honest,
  critical, and thoughtful manner, cites them correctly and appropriately, and
  clearly explains how they support the author’s own argument.
- It offers a brief conclusion that explains what the letter or dialogue has
  contributed and what further questions related to your inquiry might be
  fruitfully explored later.
- It is well-written, clearly structured, and almost entirely free from
  grammatical errors and stylistic infelicities
** Draft 1
Some questions for me to answer first
1. What form am I writing this in?
   A letter from Plato to More
2. What is the problem, and what is its significance
   Plato believes humans are dumb in general, and they need a noble lie.
   1. Nuclear family is dumb and cannot work
   2. Private property is embedded in human nature, communism cannot work.
      Humans are selfish and only with noble lie things can work.
   3. Can complement More on their lack of law - Plato thinks law is not
      necessary given the citizens are indoctrinated by the noble lie and will
      be forced to do good. More believes that human nature itself can replace
      complicated laws.
3. What are the angles I am responding to this problem from?
*** Attempt 1: Nuclear Family
Republic(457c - 466), Utopia 83-85
- Plato: people should just mate a breed favorably. The best humans breed will
  get us the best offspring.
- More: Love is sacred and people should love each other as they are, and the
  sexual relationship which they take is a byproduct of successful marriage.
- Plato: Humans should marry, but that is just a ceremony to achieve state
  control in reproduction.
- Children born from inferior or non-guardian parents must be inferior.
- It is impossible to determine the quality of babies.
Plato for some reason met More, who was spending time with his family. Upon
Plato's visit, More was promptly surprised, but he could not recognize Plato
until the man introduced himself. For some reason, they both speak English

Plato: You must be Thomas More, I ... and had the chance to meet you. I am here
to speak to you about family. Would you have time for such a conversation?

More: Certainly. What is it so important that we must talk about families in our
first and very last meeting?

Plato: Well, since you are such a family man, we shall talk about it once and
for all. In your book "Utopia", which I imagine is an ideal city that you are
trying to construct, in a similar spirit with Kallipolis. You said that people
should live together in a small family, and have one spouse only. What is the
reason for doing so? Since Utopia is so rich, why should it not allow men to
have many wives instead? There is nothing wrong with it, especially when spouses
have already passed the ritual.

More: My dear Plato,
*** Thomas More's letter to Plato
Plato and Thomas More met, in More's time, and having read each
others' work on an ideal city, which Thomas More named as Utopia, and Plato
recorded his as Kallipolis. Both of them stroke up a conversation immediately
after recognizing each other on the street, just before More has to attend a
church service.

More: Hi Plato, your work on Kallipolis was a monumental one, but do you mind
talking about the social policies Socrates mentioned when he was describing how
it can be built?

Plato: Certainly.

More: Then let us first talk about the composition of families. Socrates
proposed the idea of shared spouses and children in Kallipolis, and that is for
the reason of having the best possible offspring in Kallipolis. This is first
driven by the fact that the "need for excellent rulers is indeed extreme"
(/Republic/ 459b). And by observing dogs and birds at Glaucon's home, we decide that since
birds and dogs have the best and most noble offspring by "breeding from the
best"(/Republic/ 459a), and "those in their prime"(/Republic/ 459b), we can have humans do the same
too and have our best people produced generation over generations in the Kallipolis.

Plato: That is true.

More: Now allow me to ask, how are humans directly equal to the animals? Humans
are clearly more superior beings than animals, for human is the species
that is superior than just normal animals, as their souls are immortal and are
unlike animals (/Utopia/ 101). Humans are also only species who "admires the
beauty of the world, enjoys any sort of scent", and "can tell the difference
between a harmony and a discord" (/Utopia/ 79). Since humans distinguished themselves from
animals via their soul, and its qualities, then having citizens with the best possible
soul is our priority. Furthermore, Socrates mentioned that in the Kallipolis,
the guardians have to be "gentle, spirited, and philosophical" (/Republic/ 375c-e), all of
which lies within the soul? One can be gentle in the looks, but evil and
calculating in the soul, spirited in the body, but cowardly when confronted with
hardships, and even more, if one is a fine philosopher, it is not easily
distinguishable from the looks. Since the human body is a mere vessel containing
the soul, which is responsible for what they do and who they are, we shall judge
a person by its soul, just like how you choose the guardians in the Kallipolis.
Since the most prized guardians of the Kallipolis are the strongest at their
thoughts, and thus are suitable to be trained to be guardians, how can we liken
the breeding of animals to humans, or much less, the guardians, whose spirits
are unparalleled?

Plato: Let me repeat your question. So you are opposing the idea of selective
breeding of citizens in Kallipolis, claiming that it might not result in
offspring with desired qualities as Socrates and Glaucon have hoped?

More: That is precisely my question.

Plato: Understand. First, let me ask you a question. I am sure you have horses
in Europe?

More: Certainly, but I think they are unlike humans in many ways.

Plato: Pray let me finish my point. Now, when you choose your horses, are the
tame-looking ones likely to be wild and unwieldy, or are they less likely to
follow order as compared to the wild stallions?

More: I think they are likely to be gentle.

Plato: So it is not entirely unreasonable if we can judge people not just by its
soul, for the body is just a case, as you will agree, which the soul resides,
and a good soul, and a desirable one, will manifest itself to a decent body. As
Socrates mentioned in Book IV, "it seems to me that a fit body doesn't by its
own virtue make the soul good, but instead that the opposite is true - a good
soul by its own virtue makes the body as good as possible." (/Republic/ 403d) If you
consider the contrapositive statement, if a body is not the best, it is unlikely
the soul is made up of amazing virtue, since if the person is of the best in his
mind, the body would not be a disappointing one.

More: That is true, but I think we reached the tough question about body and
souls, which is inherited in reproduction? Is it the just the body or it
includes the soul? This is very contentious about humans, and we have our own
belief in Christianity. Now I would like to hear more from you about this.

Plato: Then let us talk about humans. Do you think the children of thieves, will
all likely to be priests or philosophers in the future? Will they not be born,
unknowingly, with the ability to steal? Or is it more likely that a person with
virtuous family members that will grow up to become a person like his or her
parents?

More: That must be true, regarding the circumstances. However, I think these
examples do not consider the training of children in music and poetry, or even
physical training. (/Republic/ 377a) A child, even though born with a poor background, can
be trained to become a philosopher as well, as long as they learn the ways of
inquiry. I think that even though the chances are higher that a guardians'
children will be of the same caliber, I still think such an outright exclusion
and disregard to humans' ability to learn is contrary to the fact that animals
are fundamentally different from humans. Will humans not learn to adopt the
qualities of gentle, spirited and philosophical as you mentioned, with
appropriate training?

Plato: It is true, but Kallipolis is not created to ensure the happiness and
fairness for each and every of its citizen, but the city is virtuous and happy
as a whole. (/Republic/ 421b) Have you not seen the problem with too many mouths in a
family? The children who are weakest usually suffer from diseases and die a
young age, or from malnourishment. If we try to nurture too many possible
guardians by not selecting them based on breed as you suggested, I am afraid we
will fall to the same fate of overcommitment. Kallipolis' source of wealth and
happiness is by the virtuous guardians who keep the city safe and under control,
and only having an appropriately large amount of them can make sure by the
generations, the city will not fall due to the lack of virtuous guardians. This
way, the makers in the city will have the greatest happiness too, not because of
the multitude in opportunity for sexual intercourse, but because they are
protected by able guardians.

More: So your point is in order to save time, we should just use the heuristics
given by a person's body to assess him for whether he is suitable for mating,
and bear the assumption that guardians are guaranteed to have a higher
probability of having good offspring, in the hope that the future generation
will turn out to be the same, if not better? And this will be regardless of
whether it is fair to each and every soul in Kallipolis as we care only about
the future of the city itself rather than personal gains, even if it means to
live in pain or the unhappiness of not being able to have the chance to
reproduce, and have your own offspring, as I would think is what humans are
naturally conditioned to do.

Plato: Indeed they would not be sad about it, since they believe in the noble
lie that each of them are earthborn brothers, and will fight together to defend
the land in which they live (/Republic/ 414e), as the survival and prosperity of the city
would be their ultimate goal, even if it means to suffer personal losses. In
terms of having offspring, all citizens in Kallipolis will have many mothers and
fathers, also siblings and children too (/Republic/ 461d), and it is this shared ownership
that will overcome the selfish sense of private property.

More: Indeed that is how it is arranged in Kallipolis. I doubt it will work in
any other contemporary settings, including the Utopia I described in my book,
but I can see now how Socrates designed the Kallipolis to be.

Plato: Precisely.

More: Plato, have you also mentioned that all these are packaged in "falsehood
and deception for the benefit of those they rule" by the rulers, which are a
form of drug (/Republic/ 459c). In the case of marriage, the rulers will allow
sophisticated lotteries to favorably pick the best "breed" to marry each other.
Have you thought of what could happen if one day, an inquisitive mind discover
the scheme behind the curtains, and the makers of Kallipolis find out that they
are manipulated to give up their ability to reproduce? You must agree with me
that all animals and humans alike, are "driven by innate necessity to have sex
with one another" (/Republic/ 458d)? Just like you being robbed of your food, will you not
be enraged if you are denied of opportunity to marry someone?

Plato: One certainly will.

More: Now how do you deal with those who saw through the scheme of manipulation
and deem Utopia an unfair city, where the citizens are mindless puppet drugged
with lies and falsehood? Will this not put Kallipolis in danger as this
falsehood is the basis of the building of the city?

Plato: Those who reach such a level of comprehension and intellect, are
extremely rare, for normal humans are incapable of such reasoning without a
philosophical mind. If they truly understand, they should see all the more why
these are put in place; it is to grant the whole city happiness as we mentioned,
not in its parts, but as a whole.

More: I see. I have a church service to attend, so we have to end this
conversation now. I think we can safely say that Socrates likely to have thought
of people as largely incapable of the inquisition of knowledge, and humans are
not much different from animals as they both can possess common qualities, such
as being gentle or spirited? And on the assumption that the noble lie can hold
the city together, people would be fine to be given up their ability to marry
whoever they like as they will accept their marriage arrangement by the rulers?

Plato: I think that is an accurate conclusion for our conversation.

* Week 6 Thursday - Cinnamonia
** Political
*** Decentrailzed government by a few constitutional laws
*** The rest have their own laws, and may the best system emerge victorious
Like the religious system in Utopia
*** Cons: hard to reconcile, for example gun laws in US
** Economic
*** Dual-tier
**** Necessities are paid for
Instead of money, give them electricity, food, water, shelter etc (Universal
Basic Services)
**** More work more pay
However it is hard to regulate how long they work for different professions
**** Cons
However the best states will attract the most citizens, like US states
which might cause overpopulation due to the freedom of movement
** Community, Health, Family
*** Do what you are good at
and leave the rest for AI. If AI is good enough, it can do most of the jobs, and
people can choose what they wanna do
*** Nuclear family
*** Conflict between state intervention and personal freedom/liberty
Which is a problem in Utopia, since we would imagine both in an ideal city
**** Possible solution:
With sufficient education for people to think rationally, and choose the best
option for them.
** Tech and sustainability
Both of these need education/noble lie from young, since we are very idealistic
in forming our policies
*** Sustainable energy
*** Sharing of technology - Open Source
* Week 7 Monday - Walden Two, Chap 8-11
** My reading notes
*** Chapter 8
- 1200 credits a year to get free bills
- currently it is 1h/credit
- unpleasant or unpopular jobs have higher credits, and vice versa
- Workers, Planners, Managers and Scientists
  - Planners make policies and manage managers
    Salary is 600 a year, 2 credits per day, 1 of which physical labor
  - Managers are admin guys of respective professions
  - Scientist same income as manager, 2/3 per day
    - no pure science
    - "A leisure class would grow like a cancer until the strain upon the rest
      of the community became intolerable" (50)
- We must not let big muscles atrophy (52)
- four is more than half of eight. We work more skillfully and faster during the
  first hours of the day (53)
  - Especially you are working for yourself not your boss
- No need for insurance or tavern, since alcohol is to "counteract the fatigue
  and boredom of a mismanaged society"
- Request visitors to work 2 credits a day, and can bring half away
  - However residents need to surrender all income to walden 2
*** Chapter 9
- Decide to work as window cleaners to pay their credits
- Found that it is at first "like prisoners", then "easier than grading or
  reading term papers"
*** Chapter 10
- Frazier says they get rid of hard work, instead of workers in trying times
- Frazier keeps food stock enough for a year, which Castle commented "like
  locusts" (70)
- Walden Two might have some fatal flaw.(71) Frazier seldom know what he was
  talking about, a rank amateur in rural arts.
- 3 rooms, like astronaut's entry, for farmers to get rid their odor to make the
  job more popular (72)
- no one thanked her... this was in accordance of the Walden Two code. (75)
- The Lovely Lady in thin air on thin thread analogy
  - "We prefer the illusion, too... we enjoy floating in air." (76)
  - We are not free from the economic law, but leisure is our levitation.
*** Chapter 11
- What makes a poster interesting, conditional behavior (77)
- What do you do during free time?
- Walden 2 produces art as abundantly as technology
- Golden Age is unintentional. We let civilization run away and see what we can
  do with her lovely colt (Mg chills)
- Everyone is encouraged to learn the arts, and perform or present it as people
  consume them regularly
- Musical families and centers are the environment to condition and make the
  most out of genes.
** Presentation: Walden Two and behaviorism
*** Skinner and Behaviorism
Walden Two uses positive conditioning mainly
- Classical Conditioning
  stimulus, like Pavlov's dog
- Operant Conditioning
  give consequence to an action, eg giving more screen time for practicing piano
Skinner believes there is no free will, but only *reaction to the environment*
*** Construction of Walden Two
- (46) We don't propagandize. That's a basic principle.
  When asked about how to make people select undesirable jobs
- Naturalism
  *Definition*: all beings and phenomenon in the universe are natural and can be
  explained by science.
**** Conditioning examples
Behavior -> Consequence -> New Behavior
1. Sheep touch electric fence -> Sheep electrocuted -> Sheep shuns away
   And thus we can use a string
2. Visit Walden Two -> Guilty -> Work in Walden Two
*** Criticisms against Skinner
1. Takes away purpose, mind and freedom
   Counter: naturalizes instead
2. Behavioral conditioning
   Counter: every civilization does, it, question is whether it is *dehumanizing*
*** Think about:
1. How does Singapore government condition the citizens via policies?
   - Meritocracy itself is a conditioning
     people might lose faith in the society if they work hard and not do well
   - Prof: Giving you grades is conditioning you to work harder
   - Cigarette packs having deterring images
2. If Singapore politicians were to read Walden Two, how would it influence
   their societal ideals?
3. How do you think the conditioning done to us affected our idea of an ideal
   state?
** Discussions
*** Labor market in Walden Two
Is "raising the credits" for more needed, less wanted jobs a better way to
organize the job market?
- Pride and prestige in jobs
  People are not thanked in the society.
  Doctors are not called doctors in Walden Two, stripped away their title
- The paradox that the most menial jobs are the highest hours
*** Behaviorism vs Genetics
- Frazier: culture (environment) is the key to producing artistic talents, genes
  not so
* Week 7 Thursday - Walden Two, Chap 12-15
** Reading notes
*** Chapter 12 - The Nursery
- Babies until 1 stay in a nursery, like an "aquarium" as "fishes (87)"
- Sleep on plastic sheets, without clothing, temperature control, controlled and
  unnatural environment
- obstacles and nuisances are introduced slowly (89)
*** Chapter 13, 14 - Emotional conditioning
- controlled groups for children in groups or exposure to contagious diseases (91)
- using behavorial engineering to eliminate negative emotions such as "anger,
  fear and rage" (92,93)
- Frazier and his planner, Simmons, seek to learn the ways to teach self-control.
- Jesus's technique is to practice the opposite emotion (96)
- But by promising paradise or hellfire might not be effective
- Lollipop and powdered sugar - teach the children to practice self-control by
  taking it out of sight. Then train their tolerances.
- Soup and temptation - first wait for 5 minutes by a song, and then practice by
  coin flips. Heads eat, tails wait for 5 minutes
- "the community must gain their loyalty, when they discover the fears and
  jealousies and diffidences in the world at large." (103)
- "Triumph over nature and over oneself, yes. But over others, never."
- "The unhappiness we deliberately impose are far milder than the normal
  unhappiness from which we offer protection." (104)
*** Chapter 15 - The schooling system
- "we also don't require all our children to develop the same abilities or
  skills." (110)
- "What are these distinctions, anyway, once you have separated education from
  the administration of education?" (111)
- Hands-on, practical education, learn things that are valuable and relevant
- "We teach anatomy in the slaughterhouse, botany in the field..." (112)
- "Freedom is a question, isn't it?" (118)
*** Chapter 16
- Teenage love is encouraged and people can bear children a few years after they
  are physically able
- "We say it wont last... of course!... A thousand forces conspire against it,
  but they are not forces of the nature, but those of an ill-organized society".
- Teens will be financially supported by the state to get married and bear
  children
- In Walden Two, women finish reproducing by around 23, and since the burden of
  childcare is taken care of by the society, she is free to explore her career.
  (122)
- "Puppy love tends not to be overtly sexual at all. It's usually highly
  idealistic." If a manager feels the couple has great discrepancy in
  intellectual ability or temperament, the marriage is at least postponed or
  cancelled.

*** Chapter 17 - Married life
- Married couples sleep in separate rooms. This is claimed to promote "health,
  convenience and personal freedom" in life after childbearing.
- "Instead of inviting promiscuity, it perpetuates loyalty and ensures any
  continuing affection is genuine."
- "Free affection" and the principle "seduction not expected", so opposite sexes
  can make friends with each other normally and "that goes a long way towards
  satisfying the needs which lead to promiscuity elsewhere."(129)
- Divorce is made pretty much painless with the assessment of a psychologist
  (131)
- The attenuation of the parent-child bond
  1. requires other adults to show affection to children not of their own
  2. allows childless adults to care and show affection
  3. make divorce less traumatic for the children
- The "tradition of slavery" where women "have no choice but to work as a cook
  and cleaning woman", disillusions our false promise of equality in education
  (135-6)
** Presentation
** Debate
* Week 8 Monday - Walden Two, Chap 20-24
** Reading
*** Chap 18-19 (Not assigned)
- Burris, Steve and Rodge went for heavy work, during which Rodge showed great
  interest in joining Walden Two, but Babara, his girlfriend is opposed to this
  way of living, which held him back.
- During dinner, Burris asked Frazier whether Walden Two learnt anything from
  similar communities in the past, and after strong denial at first, Frazier
  said such communities are often idealistically carrying out principles rather
  than experimenting with strategies that improve, which caused their downfall.
  (141)
*** Chapter 20 - The Good Life
- The Good Life is
  - good health
  - not idleness, but enjoyable, voluntary work
  - chance to exercise talents and abilities
  - intimate and satisfying personal contacts
  - relaxation and rest
  - and Frazier claims that this is exhaustive.
- Castle notes that this is under the assumption that human is good by nature,
  which Frazier achieves by behavourial engineering.
- Walden Code:
  - The Ten Commandments
  - Some trivial ones include:
    - Don't talk to outsiders about the affairs of the community.
      Except for Planners, and certain cases
    - (Apprenticeship rule) Explain your work to any member who is interested.
    - Don't gossip about the personal relations of members
    - Don't wait too be introduced before speaking to a stranger, nor bother to
      make introductions if no relevant information is to be communicated.
      Introductions are solely for the purpose of communicating information.
    - The expression of boredom is accepted here to prevent time being wasted.
      The person does not get offended because this is a norm, and this rule
      rids the speaker of the fear of being boring.
    - Disallow public discussion on disagreement on any rule. You can only speak
      to Manager, or Planner if managers reject your disagreement.
    - Cannot publicly display gratitude to any specific person
- Frazier unscientifically insists that the success of Walden Two is due to the
  self control the residents acquired when they were young. (164)
*** Chapter 21 and 22: Healthcare and Public relations
- Walden Two has exceptional healthcare too, similar to Utopia. The dentists,
  for example, have almost nothing to do.
- Castle argues the doctors' training come from the state, rather than Walden Two.
- Frazier: previously designed utopias are in a fictitious world where people
  behave in a different way, but Walden Two uses behavorial engineering to
  create it now and here (180)
- Frazier has no faith in human nature (182), but engineers it to be socially capable.
- Members do not take part in politics and vote as instructed by the Political
  Manager's "Walden Ticket" (183)
- Free to practice any religion, but members have Sunday meetings to
  indoctrinate the Walden Code (185). Walden as a religion provides: (186)
  1. Aid to the sick and needy (healthcare)
  2. Comfort in time of loss (by psychologists)
  3. Genuine comfort - sympathy and affection of many friends (community love)
  4. Hope for a better future (now and here)
*** Chapter 23: Keeping people in Walden Two
- Indoctrination is the safest way of assuring failure. (192)
- Children in Walden Two know the whole outside world and its truth in its
  entirety. With the poverty and suffering, they might just appreciate Walden
  Two even more.
- Assignment: to find poverty in luxury as fast as possible
- Indoctrination masks the happiness and other variables in a community, making
  it unsuitable for experimentation of the rules and therefore incapable of
  progress to stay relevant in changing times.
** Presentation: Frazier - Tyrant or Genius?
*** Frazier, Burris and Skinner
- Frazier acted as a mouthpiece for Skinner
- Fulfilled his God Complex by able to create a fictitious world himself
- Skinner can dabble with his extremist views, on "carrying out" experiments on
  humans
- Burris ans Frazier act like two sides of Skinner
*** Their views
**** Castle's view of Frazier
- Frazier is the midget chess player behind Walden Two
- Frazier might me thought of as ingenious, if his actions are without moral repercussions
- More of a tyrant - sadistic, dubious
**** Burris
**** Steve and Mary
- Too good to be true, must have some kind of catch
** Democracy
- stifling voices from the people
- planner came out with the code, which
*** Points raised
- dissent only raised to the planners
- abduction of scientific method (how) to justify his beliefs
* Week 8 Thursday - Walden Two, Chap 28-29, 32-33
** Reading
*** Chapter 28, 29
- Frazier: "I have no more interest in you as material for a scientific
  investigation than if I were, an anatomist". (228)
- Frazier has a very messy room.
- Frazier admits he is cold and calculating, but also raising an explanation
  about him not being a product of walden two.
- Democracy is ineffective, much less than small community like Walden Two.
- Freedom - what is freedom? The feeling of freedom, oppression(247)
- Problem about Russia's communism
  1. Decline in the experimental spirit
  2. Over-propogandization, which prevents progress
  3. The use of heroes
  4. Use of power
** Presentation - Walden Two - Dystopia or Utopia?
*** Definition
- Utopia - significantly better than our society
- Dystopia - worse
*** Distinguishing factors between Utopia and Dystopia
1. Would you be happy in Walden Two?
*** What did Walden Two achieve?
- Achieves the basic needs in Maslow's hierarchy of needs
- Freedom - is forced to go through behavourial engineering free?
- Oppressed
- Free choice - in Walden Two you cannot choose your method of governance
- Positive reinforcement - nudged instead of forced to change your way, is
  pleasant to some extent
- Dehumanizing - serve the community only but not for yourself
*** Our problem with Frazier?
- Newman, in the Behavioral Analyst: Walden Two does not provoke the crucial
  sympathy for reader to accept Walden Two
- God complex, but that should not be the only reason to deny Walden Two
*** Questions:
1. Walden Two makes everyone happy, but why is it not a Utopia?
   Answer: Ethics play a part too
2. Life, Liberty and the pursuit of Happiness
   Negative vs Positive Liberty
   https://en.wikipedia.org/wiki/Two_Concepts_of_Liberty
3. Happiness - is being cheerful and in a good mood happiness?
** Discussion
*** What is human dignity?
1. Religious - Immanuel Kant
2. Catholic church
*** Control and monopoly in Walden Two
- Douglas:
  Democracy assumed good human nature vs Democracy is designed for the flaws in
  human nature
- Deanna:
  Planner/Manager controlling everyone's mind is dangerous
- Kindergarten's report card - behavioral conditioning
- There is no government without coercion - how do they deal with uprising?
  - Perhaps they can leave if dissatisfied?
* Week 9 Monday - Brave New World, Chap 1-3
** Reading notes
*** One
-
** Presentation
*** Historical background
**** Adolus Huxley
- Grandfather is a student of Charles Darwin
- Son of writer father
- Brothers involved in the British Eugenic Movement
  - Humankind can be "improved" through selective breeding
  - Happened in the 1920-30s, during the great depression and the rise of
    facism/communism
  - exposition of a totalitarian state, with clear references to communist
    personals such as Marx and Trotsky
*** Setting
- Bokanovsky's Process
- Castes: Alpha to Epsilon, progressively dumber
- Soma: drug to ensure unquestioning euphoria
- Reserves: Savages, in New Mexico
- Sex as a means to control the society, by satisfying their primal desires and
  have nothing else to ask for or rebel against
- Loss of identity: 1M people sharing 10K names - around 100 per name
*** Thoughts
| John (the savage)                           | Lenina                                    |
|---------------------------------------------+-------------------------------------------|
| Loss of free will                           | We are joyful under drugs therefore happy |
| Happiness is conditioned, sewage is not fun | Sex, drugs, pleasure, orgies. Utopia?     |
| Happiness cannot come by without suffering  | Unlimited pleasure, no pain               |
| The problem is having no contrast?          |                                           |
*** The social contract
Trading freedom of happiness?
** Lecture
*** Dystopia
- Anti-utopia, the negative or opposite of utopia
- The Golden Age for Utopia - between WW1 and WW2
- "The satire is a much upon contemporary materialism and consumerism as upon
  the eugenic super state..."
- Encourage resistance? Submission?
* Week 9 Thursday - Brave New World
** Presentation
*** Why Brave New World?
- Portray the future given 1930 scientific advances
- Critique the Wellsian Utopia
*** BNW revisited?
- written in the 1950s, 30 years after BNW
*** Overpopulation
From 3B in 1958 to 7.7B in 2020
**** Resources?
- Water
- Oil
- Phosphorus
*** Chemical Persuasion
** Discussion
*** Soma
Wing Sum: Soma as a way to quell dissent. When people face problem they will
always turn to soma
Jing Wen: Soma is a form of enjoyment similar to playing piano.
- Soma acts a an escape
- Assumption: to achieve human progress we need the strength to face adversity
- Soma brings mutual exclusivity between happiness and progress
- Hedonistic point of view: everything we do is to make money to gain happiness
- State marketing soma to quell dissent
- Can you self regulate - take less soma - so you can work - so you can buy soma
*** Hypnopaedia
- Hypnopaedia knowledge is static and resistant to change
- Similar to parents' teaching?
* Week 10 Monday - Smart Nation
** Forum Post
- Hacking and progress, move fast break things?
- Problem in government having the worst technology?
- Allowing progress in different Utopias:
  - Kallipolis allows rulers to define rigid rules only, have little chance to
    reflect and face their own mistakes
  - Utopia holds priests at a high position to administer
  - Walden Two has planners who decide
  - Brave New World has strictly controlled progress
- What is the prerequisite for a Smart Nation?
  How to embrace the flipside of technology? Privacy concerns, cybersecurity,
  even less efficiency than f2f (think self-ordering machines)
** Introduction
- Retrotopia - instead of building utopia, look back to the past and reactivate
  that "golden age"
- China: traditional values, America: make America great *Again*
- However Singapore still strives for Utopia: LHL called it in 2008 speech
  "Garden of Eden", a mythical utopia
- The Smart Nation: looking at its mission statement (2014), is it utopia?
*** Jared - MCCY
- Get government and people to talk to each other?
- Discussions are often ideal/and utopian
- Engagement as a spectrum
  Government give, you take (transaction) <------> People connect with
  government, as per the silver generation initiative where volunteering
- Co-creation, citizens get more power to come out with projects and government
  do it (?)
- MCCY think of tech as a means. Stepping stone
- Smart Nation as providing more convenience, but MCCY want to create a space
  for people to connect by creating redundancy in things so people can
  complain???
- Making life difficult as a thinking and promoting community cohesion and
  cooperation
*** Talitha - GovTech
- TraceTogether and curated, official WhatsApp messages on latest info
- Homa - Tracking SHN & LOA
- Tracking distribution of vouchers
- Authoritarian governments can dictate technological growth
** Discussion
1. Arts and Humanities
2. Data security and Privacy
3. A moving goalpost?
   - The details are not laid out of what is the ultimate goal of Smart Nation is
   - Constant experimentation as per Walden Two?
4. Loss of manufacturing jobs and what about the elderly
   - What can we do to ensure elderly learn?
   - Is it possible to retrain all workers?
5. Are smart solutions always the best?
* Week 10 Thursday
** Reading
- Smart urbanism: an urban response to the explosive growth in the production of
  data
*** Promises
- Can deal with urban maladies such as traffic congestion and pollution, etc
- Distribution of resources based on data (rather than politicians' view)
*** Premises
- Data-driven feedback loops: if tech is the infrastructure that forms the
  backbone of smart urbanism, then data are the oxygen that brings the body -
  the smart city - to life.
*** Smart Nation in Singapore
*** Four paradoxes
- ideology/praxis
- efficiency/control
- access/choice
- smart governance/smart citizenship
*** Fourthspace
** Presentation
minority report
psycho-pass
* Role-playing Brainstorming
** Section 1 - The introduction
Narrator: MM one day decides to visit a reserve, with a primitive, savage
country call Malaysia. He was doing his routine inspection, and the leader of
this savage country, Najib came to meet him alongside with a visiting
professor from [insert university or castle's hometown]

Najib: Welcome to Malaysia, truly Asia. I am Mohammad Najib bin Tun Haji Abdul
Razak, the 6th prime minister of Malaysia. My hobby is, well, making money and
drinking coconut water.

Castle: [says hi]

MM: [says hi, mentions that he is one of the supreme rulers, which pique najib's
interest]

Najib: Wow, so you get to do whatever you want to the people? And do you get
infinite amount of money from that? How do you even run away from law? My team
of lawyers and police officer always had to keep me out of trouble, although
that does cost some peanut money.

Castle: [appears to be shocked by najib, asks what he did]

Najib: HOHOHO, last time I got some extra pocket money, a few million in my bank
account but the stupid reporters thought they caught me, but i just said that my
dear brother in UAE shipped it to me as a birthday present! And I bought a few
handbags for my wife Rosmah too. Eh MM, what do you exactly do?

MM: [more in-depth description of his power's extent]

Najib: Wow sounds like your people is even stupider than mine! Mine are like a
bunch of sheeps who sometime try to stop what I do. I would be such a great
leader in Brave New World!

MM: [scorns]

Najib: But that is horrible! What do you mean by I am a Gamma minus?

Castle: My dear friend, i think you are doomed hehe [pls edit]

MM: [explains blah]


MM visits reserve containing Msia
MM describes BNW while Najib concur with his experience ruling msia and corrupting

Unlimited power of leaders
No voting rights

MM scorns, says Najib’s intelligence is that of a Delta, infused by coconut skin in his embryo (coconuts are actually quite nutritious how about salted fish kidney poisoning ono)
Najib learns about his rightful treatment in BNW
* Week 11 Monday
** Eugenics
- Walden Two and frazier would not agree with eugenics because he believes
  people are conditioned, and less born.
- Singapore cannot abandon nuclear family because Singapore doesn't have the
  background for experimentation.
** Emotions
- Frazier: we don't avoid emotions, we deal with them at a very young age (to
  get rid of them)
- Human emotions can be a strength and a source of power
** Technology to save labour
- MM: Yes, we should, why not? Frazier the same
- Modern: leisure might make us feel less fulfilled
- Frazier: we need work, but just not that much.
-
* Final Paper Proposal
** Brainstorming Draft 1
- I am trying to learn about ???
- because I want to find out ???
- in order to help my reader understand

Possible ideas:
- More's Utopia: reversing gold's value
  - Behavioral engineering to make sure there is no unrest
  - No inequality
  - Compare to walden two
  - compare to prison economics
- Singapore Smart city
- Keeping it relevant down the generations, our examples tend to be first
  generation or creators, except for
- Propaganda
- Freedom of choice: walden two you don't have democracy, plato you don't have
  freedom of truth, more's utopia you have engineered truth
- Amount and length of work (also with the nature) and happiness
  - If everyone work faster, everyone has to work more too
** Draft 1 - Jobs and happiness
*** Brainstorming and title setting
Questions:
- Utopia is a place where people seek happiness (for all, hopefully). One of the
  things people do most of their adult life is their jobs. What kind of job
  makes people happy? How do different utopias address jobs?
- Fundamental question: how do jobs make people happy? Is it direct happiness
  from jobs (ie enjoyment in my own craft and creation) or indirect happiness
  (ie things that follow from the job that makes me happy, ie possession?)
  - Direct happiness see Deep Work.
  - Indirect happiness need to find theory of possession and security
- Connection between Maslow's hierarchy of needs and jobs - some utopian societies
  aims to provide for the basic physiological needs and emotional needs, leaving
  people only the higher levels to fulfill
  - Look at some other theories of happiness. [[https://www.authentichappiness.sas.upenn.edu/newsletters/authentichappiness/happiness][upenn happiness]]
    1. [[https://en.wikipedia.org/wiki/Self-determination_theory]]
    2. https://en.wikipedia.org/wiki/Need_theory
- Assuming people do not need jobs to feel fulfilled, jobs are now redundant.
  Society however needs people to create that value and serve each other to keep
  it running. Therefore we see forced labour to do the necessary in Walden Two
  and More's Utopia.

Attempt at topic
Jobs are the key to happiness.
Meaning of jobs in impacting happiness in a Utopia society.
A claim, specific:
Focused and minimized jobs are the key to happiness in Utopian societies.

Focused as in deep work, satisfaction from doing the job itself.

- I am trying to learn about the role of jobs in a Utopian society
- because I want to find out how the nature of jobs one does can impact their
  happiness
- in order to help my reader acquire some pointers to choosing a job in the
  future.
*** Outlining
Title (tentative): Nature of jobs in selected Utopian communities and their
relationship to happiness

Context: Utopias are places where people are promised a good life, often
entailing happiness. Utopian societies are not mythical, they still need their
residents to work to create value and keep the society working, as resources
don't appear out of thin air, goods and services need to be produced by the
working public.

Motive: Under this assumption, there is a seemingly contradictory relationship
arising - that between work and happiness. Working is not the most enjoyable
experience to most adults, yet societies, even Utopian ones need people to work
to achieve a happy and good life, which seems contradictory in Utopian societies.

Thesis: Work does not make people happy. I claim that focused and minimized work
are the key to achieving happiness in Utopian societies, and we can even adapt
these principles to modern context to make people have a happier relationship
with their jobs.

Points to mention:
1. People do jobs they enjoy, and that derives meaning for them. An example is
   Ikigai. We can also argue that by doing the job your are best at (and
   optionally, that job only) can yield the most satisfaction for the individual.
   - In Kallipolis, everyone is only allowed to work at what they are best at
     only. Although sounds like a lack of freedom, I claim that this builds the
     foundation of trust and interdependence within the city. Reason being:
     - Doing what you are best at means for any other tasks you are bad at,
       there is someone better than you at it
     - Having someone to do that for you well gives you the peace of mind that
       any other problem of yours will be resolved by a professional
     - This symbiotic relationship reinforces the concept of the whole city
       together as a single entity.
   - Individually, people can gain satisfaction by mastering a skill. Check
     Ikigai and Deep Work.
2. Obviously, if under the assumption that most jobs are undesirable, it is
   important to keep them to a minimum, sufficient to keep the city running.
   This is prevalent in socialist Utopian societies such as More's Utopia and
   Walden Two.
   - More's Utopia allow only 6 hours of work everyday, and everyone takes turns
     to do farming, in two-year shifts (51). They have a tendency to use
     technology to reduce their work, such as applying gentle heat to the eggs
     so that they hatch faster. Everyone has a main job of farming, and is
     taught a skill (or two) on something they like.
   - Walden Two is a big fan of removing redundant, unnecessary work using
     technology and social engineering so people don't need to work that hard,
     usually only for four hours a day. Examples include using glass plates and
     peeling corn efficiently (?).
   - It is important to throw doubt on this: In a socialist society, people
     would naturally want as little work as possible, and shout "I have done my
     share!" as early as possible everyday. With this mentality, what is the
     purpose of jobs other than for the good of the society? If people are doing
     it, will they be reluctant because there is no tangible benefit?
     - Walden Two is not thankful to anything
     - More's Utopia has no idea of possession or currency, there is nothing for
       you to hoard to feel secure about :(
3. Jobs and happiness in today's context. Even though we do not live in a
   Utopian society, the idea of UBI is a rather curious experimentation of
   mixing socialist with capital possession. Unhappiness in workplace often
   arise from stress, disproportionate benefit, and [idk any more i'm not even
   working, i need to research]. We explore how the two ideas of having focused,
   minimized work can lead to happiness in our society.
* Final Paper

** Outline
*** Motto
I am trying to learn about *Singapore's framing of Smart Nation as a Utopia*
because I want to find out *how relevant is Smart Nation as a Utopia and what
are the consequences of framing Smart Nation as a Utopia*, in order to help my
reader understand the *inaccuracies, idiosyncrasies and danger of framing
Singapore's Smart Nation initiative as a Utopia.*

Context: Singapore has Smart Nation to build a better future for everyone
Motive: I think this is misleading, it is not a utopia.
Thesis: Smart Nation is not a Utopia
*** Points
1. Technology is not a silver bullet, it is not suitable for every single aspect
   of urban living such as ???
   - Example: too many apps to report faulty?
   - Old people panic button fail?
   - Jet: developing apps for autistic kids might even provide a virtual world
     and discourage them from facing the real world.
   - Jerald: Making things hard to promote cohesion, rather than having
     convenient apps
2. Technology is often not the solution, but a tool to achieve the solution
   formulated via humanities research.
   - Eg. machine learning and pattern recognition learns only what humans
     perceive, including the biases we already have
   - For example, machines can learn to be racist due to the labeling.
   - We need to decide what to do with the result, instead of just thinking
     about the results. For example, college admission models learn how to
     discriminate people of poor background due the their correlated poor
     education.
3. Smart Nation, when implemented in Singapore, will discriminate heavily
   against people who are not tech savvy, and this lacks the equality which
   every utopia tries to achieve.
   - Eg. In Walden Two, everyone work for the same cridit and is guaranteed ways
     to earn that credit regardless of their abilities. However in a situation
     where technological solutions are the only way to go, especially with
     Singapore's aging population, many are going to be neglected.
   - https://www.mci.gov.sg/en/portfolios/digital-readiness/digital-readiness-blueprint
   - There are many differences in a Smart City and the current Singapore urban
     city, despite effort made to bridge the gap:
     1. On data collection, and personal privacy. Many are giving away their
        privacy to make a smart city (which feeds on data) successful, and this
        requires ample education and research about how privacy and public good
        can be balanced.
     2. Other than the lack of technological competency, there is reluctance in
        accepting technological solutions too. This together with misuse greatly
        reduces the effectiveness of technological solutions.
*** Conclusion/misc points
- Smart nation is not a retrotopia, but is forward looking and essential for
  singapore's survival; however it lacks in being utopia, although building it
  takes time.
- Some sacrifices have to be made (such as the minority that are not well off
  with tech) and some details are pending confirmation or solidifying as to how
  to carry out data analytic tasks
- Unlike Utopias with specific goals and concrete construct/structure, the Smart
  Nation initiative seems like just another push for digital literacy and
  technological advancement in Singapore.
** Papers and ideas
*** Kong & Woods cite:kong18_ideol_align_smart_urban_singap
**** Introduction
- "Smart Urbanism" is adopted as a panacea for urban environments around the world.
- Assumes that complex social situations can be disassembled into neatly
  defined problems that can be solved or optimized through computation.
  cite:Kitchin_2013
**** Promises of Smart Urbanism
- It is inevitable with the technology humans have produced, is popular.
- It aims to be faster and better than anything that came before, promising optimal
  speed, efficiency and convenience.
- It is smart because of its efficient and automated feedback loops
- Resource allocation will be optimised based on the irrefutable logic of data
  rather than the decisions of politicians, resulting in what has been termed as
  a 'post-political' world of fairness and equality. cite:Wiig_2016
**** Premises of Smart Urbanism
***** Data driven feedback loops
- Effective monitoring, management and regulation of what is happening
  within a city
- Concern about how data are conceived, collected and legitimized for use in
  urban politics and policy making.
- Unequal access to data causes and inequality in power.
***** Effective public-private relationships
- Successful urbanism depends on public sector agencies to relinquish
* UPI2211 Final Paper
#+latex_header: \usepackage[citestyle=numeric,bibstyle=apa, hyperref=true,backref=true,maxcitenames=3,url=true,backend=biber,natbib=true] {biblatex}
#+latex_header: \addbibresource{final.bib}
# 367+1004+421+535
** Introduction
# 427-63 = 367 words
In the Smart Nation Launch Speech in 2014 cite:lhl2014_smart_nation, Singapore
Prime Minister Lee Hsien Loong announced the Smart Nation initiative to make
Singapore into "a nation where people live meaningful and fulfilled lives,
enabled seamlessly by technology." In his speech, he listed numerous ways where
technology is deployed to create a better living environment for all
Singaporeans, from taking care of the elderly using an alert and monitoring
system to telemedicine which delivers healthcare to the homes, portraying a
Utopia full of technological solutions that are promised for Singaporeans. In an
era of rapid technological advancements, where everyone is connected virtually,
where modes of work and play are revolutionized by artificial intelligence, the
push for Smart Nation seems apt. In this initiative, Singapore goes further to
embrace technology as the deciding factor for Singapore's future and declare it
the path for Singapore to be a Utopia for its people.

However, having technology-based solutions to daily problems, and imagining a
Smart Nation as a Utopia for all Singaporeans are very different. As with other
Utopias, the Smart Nation initiative aims to create an ideal life in every
aspect for Singaporeans by using "smart" solutions, which are technological
solutions. In Lee's Speech cite:lhl2014_smart_nation, he says:

#+BEGIN_QUOTE
We want to transform our lives for the better, and we have what it takes to
achieve this vision – the capabilities and the daring to pull it all together
and make a quantum leap forward. I am looking forward to living in a Smart
Nation – better living for all of us; stronger communities in our society; and
more opportunities for all.
#+END_QUOTE

where he promises to carry out the Smart Nation initiative to form a better
society for the whole nation, deeming it as a Utopia. However, promising Smart
Nation as a Utopia brings about its dangers, as this inherently implies that
technological solutions are always beneficial and empowering, and as much as
Utopias are societies which we might aspire to work towards, they carry their
flaws as literary texts such as Plato's Republic and Skinner's Walden Two
might reveal.

In this paper, I argue that Singapore's Smart Nation initiative has its gaps
from being a Utopia, and there are threats by equating them. I will highlight
the threats of equating Singapore's Smart Nation initiative as a Utopia by
showing the inadequacy of technology as a panacea, the potential loss of
democracy under the Smart Nation initiative, and lastly, the gaps between the
Smart Nation Singapore envisioned and a Utopia.

** Technology is not a silver bullet
# 1004 including cites and headers. Might come down to around 980
First of all, there is no denying that technology often improves lives for the
better. For example, Smart Nation deploys a series of technological solutions to
everyday living in Singapore, from more well-known solutions such as e-payment
platforms PayLah! and PayNow, to the less-known Moments of Life (MOL)
applications targeting families and aging population cite:smart_nation. As
Singaporeans try out these solutions for themselves, we naturally wonder whether
tech solutions are truly the only ways to solve problems. However, as the
Smart Nation initiative is thoroughly focused on creating "Digital Economy,
Digital Government and Digital Society", sometimes the most glorious solution
does not yield the best results. When we look at digital technology as a hammer,
then everything else we see will look like nails - we will try to force our
solutions onto whatever problems we come across and omit the wealth of other
more effective, alternative solutions.

Technology might give us a worse solution or even exacerbate the existing
problem. More importantly, technology is usually a useful tool for us to
implement a solution to problems developed by the humanities. These problems
often arise when we frame Smart Nation as a Utopia, the best society that we
come across, which implies adopting technology as the only solution.

*** Low-tech, better solutions
Using the right technology to tackle a focused problem can be very effective,
but there is always a tendency to over-complicate high-tech solutions. If we
keep the mindset where Smart Nation is a Utopia and we must digitize as much as
possible, we might end up missing out on better solutions that are more
straightforward in many cases. For example, when Cinnamon College's dining hall
had to restrict the number of users to 50, students first suggested a
webcam-based artificial intelligence system to count the number of magnetic
buttons left on the board and transmit this data via the internet to the
students. As later realized, reducing the number of chairs in the dining hall
to 50 achieved the same effect with a higher rate of compliance than the digital
solution - if the students are not going to squat for the entirety of their
meals, there will always be less than 50 students eating in the dining hall at
the same time.
*** Technology might exacerbate the problem
Not every problem in the world can be solved by merely building an app,
especially when the app is the root cause of the problem. For example,
hackathons sometimes target a certain underprivileged community for the
participants to develop applications for, such as the elderly or the autistic
community. However, as the elderly are new to technological solutions, they
might not benefit from the application developed at all as their living
condition possibly cannot afford a smartphone or stable internet connection.
Applications developed for special needs children might make them more reliant
on the applications' content and overlook the intention of helping them to
integrate into society or learn valuable skills, instead of delving into the
virtual world the application has created. This example demonstrates that not
all problems can be solved by technological solutions, much less framing Smart
Nation as a Utopia and hence exaggerating the effectiveness of such solutions.
*** Technology implementations depend on solid humanities solutions
The predictive power of machine learning models is undeniable, as we have
increasingly accurate image recognition skills built into the cameras of our
smartphones, and spot-on search results and advertisements on the applications
that we use. However, the results would be far from Utopian if the data
predicted is not used to society's benefit. This is harder than it sounds,
since the machines learn essentially human-labeled data, and extrapolates them
based on our existing biases. For example, using machine learning to pile
through data of applicants of any kind makes sense - these jobs are often
time-consuming and tedious, and machines excel at doing such repetitive work.
However, it needs a sample of who are the people usually accepted, and it might
extrapolate the data from there cite:racist_robots.

For example, applicants for a job will provide their personal background
information, from education to family background, and their living areas.
However, a bad model that filters such applications may be trained to look for
some common correlation between rejected applicants, such as being of a certain
race or living under the same postcode. This creates a problem, where people
from a poor neighborhood lacking proper education will be discriminated in
getting the job, or merely because of the race of their neighbors. Furthermore,
predictive analytics may even create a self-fulfilling prophecy.

In Cathy O'Neil's book, /Weapons of Math Destruction/ cite:wmd how mathematical
models may go wrong, a crime prediction system, /PredPol/ was used to forecast
the number of crime happenings in a neighborhood in Reading, Pennsylvania
cite:lum16_to_predic_serve. The bias happens when the law enforcement team begin
more patrols in the neighborhood - they catch more people committing petty
crimes such as littering or causing a nuisance, hence making the predictive model
accurate, and more importantly, they are missing out on the unpredictable,
higher risk crime due to the effective prediction system which generates a
metric which they now can never omit. cite:wmd

In this case, technology can only aid our effort in preventing crime or
increasing efficiency in selecting applicants, but a lot of human intervention
and understanding of the intricacies of the model is essential for the effective
execution of these objectives. These problems can likely be prevented if we do
not over-rely on the technological, "smart" part of the solutions, and fall back
to our logical mind to investigate or improve the system before deploying it,
rather than worshipping such solutions as the panacea for building a city and
making all its decisions right away. Framing smart cities as a Utopia dismisses
the notion of other solutions being valuable and can lead to harmful outcomes.
** The loss of democracy
# 421 words
Lying at the core of smart urbanism is data. The generation of data relies on
digitization of real-world information. From our movements to personal identity,
to the temperature and crowdedness of the surroundings, all the data with what
is happening is being recorded down with the help of new technology.These data
are the lifeblood of smart solutions, where these numbers are crunched and
analyzed to make decisions cite:kong18_ideol_align_smart_urban_singap. This can
decide from things as small as automatically change the temperature of air
conditioner, inform someone with the congestion situation of a certain
expressway, to suggesting you what to purchase and prompting for your decisions,
to filling your news feed with targeted news, messages, and advertisements.

The loss of democracy begins with the stakeholder who owns the most data - they
get to decide with the greatest level of accuracy and have the most opportunity
to affect someone's life. Huge tech companies such as Google and Facebook hold
most of our data, as we post any photos on Instagram, comment on a post on
Facebook, or link to a service via Google accounts. This prompts the creation of
an online reenactment of the physical world, and from the various apps and services
linked to a central account, a huge number of deductions can already be made by
the company. However, data collection will only get more pervasive in the case
of Smart Nation, as not only virtual data is being collected, we are submitting
our real-life data, such as consuming pattern at supermarkets, daily movement
trajectories, even to preference in food choices via location stamps to the
"digitization" of our society.

Even today, Singapore is already deemed as a data-controlled society.
cite:Helbing2019 Having data consolidated at the hands of any party will give
them immense power to do the "big nudge" - nudging people's decisions using big
data. The pervasiveness of a single search engine can cause numerous people to
consume information from the same source, that predominate a country's thoughts,
even including the lawmakers. Most importantly, this directly threatens the
plurality and diversity of the people. This can be viewed as a kind of
conditioning, similar to that in Walden Two, where the people are condition to
get rid of hateful emotions such as anger and jealousy cite:walden_two,
consolidating data to aid a city's decision-making process will directly
sacrifice the already limited diversity of Singapore.

** Is a perfect Smart Nation a Utopia, already?
# 535 words
After 5 years of the announcement of the Smart Nation initiative, Singapore is
far from fully implementing smart solutions for the whole nation yet. It is
difficult as misuses and lack of uptake are prevalent in the community when new
technological solutions and measures are first announced. Examples are the
elderly emergency button and the mobile payment solution. When the elderly
emergency button was first introduced, the elderly were unaccepting of the new
gadget, some might not use it and deem it as troublesome. And the receptionists
are stressed due to the responsibility to immediately respond whenever the panic
button is sounded by any elderly cite:kong18_ideol_align_smart_urban_singap.
Similarly to the mobile payment system, businesses, especially smaller ones are
less keen to take up the new system due to the inherent complexity, considering
many food stalls and a good number of people dealing with payments are those who
are not tech-savvy, which include the older generation cite:elderly_shun_tech.
This gap in implementation is obvious in any creation of new Utopian community,
for example, in Plato's Republic, the creation of Kallipolis requires the
important "noble lie" for its citizen to work and live together for the land,
and protect it from any external invaders cite:republic.

A series of smart solutions will look good on any metric, but when it comes to
solving the root causes of problems, it might still be lagging. Singapore is
facing an aging population, and there has been a multitude of apps and gadgets
targeted to solve them, from teaching them to use instant messaging or video
calls, or installing panic buttons, but that still does not solve the problem of
isolation for the elderly cite:kong18_ideol_align_smart_urban_singap. Many crave
human interaction, and shoving them with new applications and smartphones will
make them feel like the environment is hostile to them since it put more stress
on them and does not address the root cause of solidarity.

Having smart solutions will indeed increase our efficiency, but the inherent
convenience might make us take the daily chores which forge our interpersonal
connections for granted. For example, tasks that we used to have to talk to
people in front of the counters to get done are now replaced by automated
applications and online procedures, and we lose the ability to connect,
understand and emphasize with one another, with different professions this way.
As Jared from the MCCY mentioned, in setting their tasks to onboard new citizens
into the Singaporean community, they often "make some of the tasks difficult"
to prompt the participants to take initiative in finishing the tasks themselves,
such as leaving individual groups to create chat groups on /WhatsApp/ on their
own. This way, Jared argues, can make them more involved in the process of
bonding and hence make their orientation process more memorable and effective. I
agree with this argument since it connects with the thought that a good life is
not necessarily one where everyone is given what they wanted, but one where
their effort is valued and rewarded
cite:fouriezos90_task_diffic_increas_thres_rewar_brain_stimul.

** Conclusion
In all, technology is not a bad solution for many modern problems. For many
problems, technology equips us with an extra tool to effectively deliver our
solution with, especially with big data and artificial intelligence, but these
come with their hidden danger as well, when technology is deemed as the only
best solution to create a Utopia. To retain our democracy and free will
in decision making, extensive humanities research have to be carried out so that
a Smart Nation can make the right policies to benefit its people.
\printbibliography
